### ISSUE TITLE
Geting this TypeError: Cannot read properties of undefined (reading 'OPUS')

### ISSUE THREAD

**Issue by BlackBox-cmd** [kabirjaipal/JUGNU-MUSIC#71]
/home/container/handlers/Client.js:63
      streamType: StreamType.OPUS, // Use opus stream for better performance
                             ^
TypeError: Cannot read properties of undefined (reading 'OPUS')
    at new JUGNU (/home/container/handlers/Client.js:63:30)
    at Object.<anonymous> (/home/container/index.js:5:16)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49
Node.js v20.16.0

**Comment by himitsu95** [comment]
Rule no 69: if code doesn't work remove the line where's the error 😆
remove the line "streamType: StreamType.OPUS," in handlers/Client.js line 63

**Comment by kabirjaipal** [comment]
Hi @BlackBox-cmd, this has been fixed in the latest version (the undefined `StreamType.OPUS` option was removed). Please update with `git pull && npm install`.
