### ISSUE TITLE
Sign in to confirm you’re not a bot

### ISSUE THREAD

**Issue by NirmaLKumar26** [kabirjaipal/JUGNU-MUSIC#72]
Error handling message: UnrecoverableError [PlayError]: https://www.youtube.com/watch?v=b6h4y8mqnik
Sign in to confirm you’re not a bot
    at Object.exports.playError (/home/container/node_modules/@distube/ytdl-core/lib/utils.js:164:12)
    at exports.getBasicInfo (/home/container/node_modules/@distube/ytdl-core/lib/info.js:46:25)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by kabirjaipal** [comment]
issue is fixed
